### PR TITLE
Dev environment test

### PR DESCRIPTION
**Pull request by lerisse**
Schema has been added plus minor test changes

### CODE REVIEW

**Comment by lerisse** [comment]
@WarrenWongCodes Here's the schema, I might have changed test to TEST just to check babel

**Comment by WarrenWongCodes** [comment]
> @WarrenWongCodes Here's the schema, I might have changed test to TEST just to check babel

Ok, I will take a look. What was the issue with the schema after all? @lerisse

**Comment by lerisse** [comment]
Updated Query

**Comment by WarrenWongCodes** [comment]
Looks good. Adding schema to production.

**Pull request closed without merging**
