### PR TITLE
Show form

### PR DESCRIPTION
**Pull request by timapar**
This definitely needs some refactoring. I'll take the input forms and make them a different component. Probably make a dialog box component, etc. All functionality works except the photo upload. And I need a user id from somewhere.

### CODE REVIEW

**Comment by WarrenWongCodes** [comment]
@timapar There was a recent merge to dev branch with Diegos code. Please make sure to pull down changes and commit prior to submitting PR.

**Comment by timapar** [comment]
That is already done

**Comment by timapar** [comment]
The whole point of the pull request is to merge it.

**Review by AndrewHuang123 — APPROVED** [review]
Looks good to go

**Pull request merged**
